server:
  port: 8088
  servlet:
    context-path: /renault
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/renault?serverTimezone=GMT%2b8
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 20000908LPFc
  jpa:
    database: mysql
    show-sql: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
